apiVersion: v1
kind: Namespace
metadata:
  name: tasawwur-rtc
  labels:
    app.kubernetes.io/name: tasawwur-rtc
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: tasawwur-rtc
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    description: "Tasawwur RTC - Real-Time Communication Platform"
    team: "tasawwur-rtc-team"
    environment: "production"

