apiVersion: apps/v1
kind: Deployment
metadata:
  name: signaling-server
  namespace: tasawwur-rtc
  labels:
    app.kubernetes.io/name: signaling-server
    app.kubernetes.io/component: signaling
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: signaling-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: signaling-server
        app.kubernetes.io/component: signaling
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: signaling-server
        image: tasawwur-rtc/signaling-server:1.0.0
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: tasawwur-rtc-config
              key: SPRING_PROFILES_ACTIVE
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: tasawwur-rtc-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: tasawwur-rtc-config
              key: REDIS_PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: tasawwur-rtc-config
              key: LOG_LEVEL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: tasawwur-rtc-config
              key: JVM_OPTS
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: signaling-server-service
  namespace: tasawwur-rtc
  labels:
    app.kubernetes.io/name: signaling-server
    app.kubernetes.io/component: signaling
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: signaling-server

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: signaling-server-hpa
  namespace: tasawwur-rtc
  labels:
    app.kubernetes.io/name: signaling-server
    app.kubernetes.io/component: signaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: signaling-server
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: signaling-server-pdb
  namespace: tasawwur-rtc
  labels:
    app.kubernetes.io/name: signaling-server
    app.kubernetes.io/component: signaling
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: signaling-server

